---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: comm1
spec:
  config: '{
          "cniVersion": "0.4.0",
          "plugins": [
            {
              "type": "macvlan",
              "capabilities": { "ips": true },
              "master": "enp225s0f0np0",
              "mode": "bridge",
              "ipam": {
                "type": "static",
                "addresses": [
                  {
                    "address": "192.168.5.10/24"
                  }
                ]
              }
            }
          ]
  }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpc-db1
  labels:
    app: tpc-db1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpc-db1
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: comm1
      labels:
        app: tpc-db1
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: tpc-db1
        image: mcr.microsoft.com/mssql/server:2022-latest
        resources:
          limits:
            cpu: 8
            memory: 24Gi
          requests:
            cpu: 8
            memory: 24Gi
        ports:
        - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_ENABLE_HADR
            value: "1"
          - name: MSSQL_AGENT_ENABLED
            value: "1"
          - name: MSSQL_SA_PASSWORD
            value: "Amd1234!!!!"
          - name: MSSQL_MEMORY_LIMIT_MB
            value: "20480"
        volumeMounts:
          - name: mssql
            mountPath: /var/opt/mssql
      restartPolicy: Always
      volumes:
        - name: mssql
          hostPath:
            path: /mnt1/db1
